owner: neonliferoleplay
repo: status

sites:
  - name: Neon Veloren Server
    url: veloren.neonlife.xyz
    port: 14004
    check: "tcp-ping"
  - name: Neon Veloren Web
    url: https://veloren.neonlife.xyz

status-website:
  cname: status.neonlife.xyz
  logoUrl: https://r2.fivemanage.com/pub/eq0fvbwml7iv.png
  name: Neon Veloren Status
  introTitle: "Estado de los servidores de **Neon Veloren**."
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://veloren.neonlife.xyz
    - title: Discord
      href: https://discord.gg/Gc9qzfMjdf
